//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeSalaryPredc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpVech
    {
        public int EmpId { get; set; }
        public string EmployeeName { get; set; }
        public string VechileName { get; set; }
        public string VechileRoute { get; set; }
        public string DriverName { get; set; }
    }
}
