//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeSalaryPredc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vechile
    {
        public int VechileId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<int> AddressId { get; set; }
        public Nullable<int> DriverId { get; set; }
        public string VechileName { get; set; }
        public string VechileRoute { get; set; }
        public string VechileNumber { get; set; }
        public Nullable<int> Capacity { get; set; }
    
        public virtual Driver Driver { get; set; }
        public virtual Address Address { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
